name: TriggerIt
version: ${pom.version}

main: au.com.addstar.triggerit.TriggerItPlugin

softdepend: [WorldGuard]

permission:
  triggerit.command.trigger:
    default: op
  triggerit.command.trigger.new:
    default: op
    children:
      triggerit.command.trigger: true
      
  triggerit.command.action.add:
    default: op
    children:
      triggerit.command.trigger: true

commands:
  trigger:
    aliases: [triggers]
    permission: triggerit.command.trigger